name: Run Daily Forecast

on:
  schedule:
    - cron: '0 02 * * *'  # Run tiap hari jam 9.00 WIB
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Hapus file CSV lama dari Git index
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git reset --hard origin/main

          git rm -f usd_idr_actual.csv || true
          git rm -f usd_idr_pred_latest.csv || true
          git rm -f usd_idr_pred_yesterday.csv || true
          git rm -f preprocessed_actual_data.csv || true

      - name: Jalankan fetch script
        run: python fetch_data.py

      - name: Jalankan forecast script
        run: python forecasting.py

      - name: Commit dan Push file CSV terbaru
        run: |
          git add *.csv

          git commit -m "Auto update CSV $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main --force
